name: '10,001'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.15887
title: '10,001 inc.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d9d0cb'
    - '#040308'
    - '#442f15'
    - '#c8af9f'
  brandStrength: 0.75
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
