name: '10,001'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.84839
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ff0000'
    - '#ff8000'
    - '#ddd6c9'
    - '#808000'
  brandStrength: 0.75
  lightness: 0.6709429605398327
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
